// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RiegoWeb.Api.Data;

#nullable disable

namespace RiegoWeb.Api.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("RiegoWeb.Api.Models.LecturaModulo", b =>
                {
                    b.Property<int>("Id_Historial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_Historial"));

                    b.Property<string>("Humedad")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Id_Modulo")
                        .HasColumnType("int");

                    b.Property<string>("LuzNivel")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Temperatura")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id_Historial");

                    b.HasIndex("Id_Modulo");

                    b.ToTable("LecturaModulo");
                });

            modelBuilder.Entity("RiegoWeb.Api.Models.Modulos", b =>
                {
                    b.Property<int>("Id_Modulo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_Modulo"));

                    b.Property<int>("Id_User")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id_Modulo");

                    b.HasIndex("Id_User");

                    b.ToTable("Modulos");
                });

            modelBuilder.Entity("RiegoWeb.Api.Models.User", b =>
                {
                    b.Property<int>("Id_User")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_User"));

                    b.Property<string>("Contraseña")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "password");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "email");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id_User");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RiegoWeb.Api.Models.LecturaModulo", b =>
                {
                    b.HasOne("RiegoWeb.Api.Models.Modulos", "Modulo")
                        .WithMany("Lecturas")
                        .HasForeignKey("Id_Modulo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Modulo");
                });

            modelBuilder.Entity("RiegoWeb.Api.Models.Modulos", b =>
                {
                    b.HasOne("RiegoWeb.Api.Models.User", "User")
                        .WithMany("Modulos")
                        .HasForeignKey("Id_User")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RiegoWeb.Api.Models.Modulos", b =>
                {
                    b.Navigation("Lecturas");
                });

            modelBuilder.Entity("RiegoWeb.Api.Models.User", b =>
                {
                    b.Navigation("Modulos");
                });
#pragma warning restore 612, 618
        }
    }
}
